### ISSUE TITLE
The Load More Button does not work on search Page after first click.

### ISSUE THREAD

**Issue by paperpluto** [devloop01/image-gallery#2]
The Load More Button does load some images on clicking on it, but when I clicked on it, it kept loading after some images were loaded and after that it did not load any images, but the loader kept loading.

Please Fix that and HELP ME!!!

PLEASE!!!

**Comment by redmundnacario** [comment]
Hi Joshua!. The api used in the app has limits so i decided to limit the calls on third time the yScroll  reaches the bottom page. Please don't forget to star my repo and follow me on github. I will follow you back. Thank you.

**Comment by devloop01** [comment]
Thanks for pointing that out. I now implemented a little workaround to fix the problem.
The issue was caused because Unsplash API is not returning more than 30 images in the response and that is causing the app to get stuck in the loading state.

### **Previous approach**
I used the "**_per_page_**" parameter to fetch the images but as soon as the value gets larger than 30 the API responses with only 30 images max but the app expects more than 30.

**syntax:** 
`
fetch("https://api.unsplash.com/search/photos/?client_id={CLIENT_ID}&query={QUERY}&per_page={AMOUNT}",{ ...options })
`

Here if the **AMOUNT** gets larger than 30 the error occurs

### **Current approach:** 
To fix that, instead of using 'per_page' and increasing that variable, I used the "**_page_**" parameter to paginate through the pages, and all the new images from the next page get added with the previous images. 

**syntax:** 
`
fetch("https://api.unsplash.com/search/photos/?client_id={CLIENT_ID}&query={QUERY}&per_page={AMOUNT}&page={PAGE}",{ ...options })
`

Here instead we increment **PAGE** which solves the problem because we are requesting images from the next page and appending it with the previous page images

> Remember the problem is in the API so if the **"_per_page_" amount** gets any larger than 30 the problem will occur again but only to counter that problem the new approach is implemented
